CodeTheWay/CodeTheWay.Web.Ui/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext() { }
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            
        }

        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Barrel> Barrel { get; set; }
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Models/Barrel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Models
{
    public class Barrel
    {

        public Guid Id { get; set; }
        public double Radius { get; set; }
        public double Height { get; set; }
        public String Content { get; set; }
        public String CurrentLocation { get; set; }

    }
}

CodeTheWay/CodeTheWay.Web.Ui/Models/ErrorViewModel.cs
using System;

namespace CodeTheWay.Web.Ui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Models
{
    public class Student
    {
        public Guid Id { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Models/ViewModels/BarrelRegistrationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Models.ViewModels
{
    public class BarrelRegistrationViewModel
    {
        public Guid Id { get; set; }
        public double Radius { get; set; }
        public double Height { get; set; }
        public String Content { get; set; }
        public String CurrentLocation { get; set; }

    }
}

CodeTheWay/CodeTheWay.Web.Ui/Controllers/BarrelController.cs
using CodeTheWay.Web.Ui.Models;
using CodeTheWay.Web.Ui.Services; //CHECK
using CodeTheWay.Web.Ui.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using CodeTheWay.Web.Ui.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeTheWay.Web.Ui.Models.ViewModels;
namespace CodeTheWay.Web.Ui.Controllers
{
    public class BarrelController : Controller
    {
        private IBarrelService BarrelService;

        public BarrelController(IBarrelService barrelService)
        {
            this.BarrelService = barrelService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await BarrelService.GetBarrels());
        }

        public async Task<IActionResult> Create()
        {
            return View(new BarrelRegistrationViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Register(BarrelRegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Radius > 0 && model.Height > 0)
                {
                    Barrel barrel = new Barrel()
                    {
                        Id = model.Id,
                        Radius = model.Radius,
                        Height = model.Height,
                        Content = model.Content,
                        CurrentLocation = model.CurrentLocation
                    };
                    var abc = await BarrelService.Create(barrel);
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var barrel = await BarrelService.GetBarrel(id);
            BarrelRegistrationViewModel list = new BarrelRegistrationViewModel()
            {
                Id = barrel.Id,
                Content = barrel.Content,
                CurrentLocation = barrel.CurrentLocation,
                Height = barrel.Height,
                Radius = barrel.Radius
            };
            return View(list);
        }
        public async Task<IActionResult> Update(Barrel model)
              {
            if (ModelState.IsValid)
            {
                if (model.Radius > 0 && model.Height > 0 && model.Content.Length > 0 && model.CurrentLocation.Length > 0)
                {
                   Barrel list = new Barrel()
                    {
                        Id = model.Id,
                        Content = model.Content,
                        CurrentLocation = model.CurrentLocation,
                        Height = model.Height,
                        Radius = model.Radius
                        
                    };
                    var barrel = await BarrelService.Update(list);
                }


                return RedirectToAction("Index");

            }
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var barrel = await BarrelService.GetBarrel(id);
            BarrelRegistrationViewModel test = new BarrelRegistrationViewModel()
            {
                Id = barrel.Id,
                Radius = barrel.Radius,
                Height = barrel.Height,
                Content = barrel.Content,
                CurrentLocation = barrel.CurrentLocation

            };
            return View(test);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var barrel = await BarrelService.GetBarrel(id);
            await BarrelService.Delete(barrel);
            return RedirectToAction("Index");
        }
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Controllers/HomeController.cs
using CodeTheWay.Web.Ui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Controllers/StudentsController.cs
using CodeTheWay.Web.Ui.Models;
using CodeTheWay.Web.Ui.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Controllers
{
    public class StudentsController : Controller
    {
        private IStudentsService StudentService;

        public StudentsController(IStudentsService studentsService)
        {
            this.StudentService = studentsService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Views/Barrel/Create.cshtml
@model CodeTheWay.Web.Ui.Models.ViewModels.BarrelRegistrationViewModel
@*
    ViewData["Title"] = "Create";
*@

<h1>Create</h1>
<form asp-action="Register">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Radius" class="control-label"></label>
        <input asp-for="Radius" class="form-control" />
        <span asp-validation-for="Radius" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Height" class="control-label"></label>
        <input asp-for="Height" class="form-control" />
        <span asp-validation-for="Height" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content" class="control-label"></label>
        <input asp-for="Content" class="form-control" />
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CurrentLocation" class="control-label">Current Location</label>
        <input asp-for="CurrentLocation" class="form-control" />
        <span asp-validation-for="CurrentLocation" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodeTheWay/CodeTheWay.Web.Ui/Views/Barrel/Details.cshtml
@model CodeTheWay.Web.Ui.Models.ViewModels.BarrelRegistrationViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container-fluid">
    <h1>Details</h1>
    <p>Radius:  @Model.Radius</p>
    <p>Height:  @Model.Height</p>
    <p>Contents: @Model.Content</p>
    <p>Current Location: @Model.CurrentLocation</p>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

CodeTheWay/CodeTheWay.Web.Ui/Views/Barrel/Edit.cshtml
@model CodeTheWay.Web.Ui.Models.ViewModels.BarrelRegistrationViewModel
@*
     ViewData["Title"] = "Edit";
*@
    @{
    }
    <h1>Edit</h1>
    <form asp-action="UpDate">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Radius" class="control-label"></label>
            <input asp-for="Radius" class="form-control" value=@Model.Radius />
            <span asp-validation-for="Radius" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Height" class="control-label"></label>
            <input asp-for="Height" class="form-control" value=@Model.Height />
            <span asp-validation-for="Height" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <input asp-for="Content" class="form-control" value=@Model.Content />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CurrentLocation" class="control-label"></label>
            <input asp-for="CurrentLocation" class="form-control" value=@Model.CurrentLocation />
            <span asp-validation-for="CurrentLocation" class="text-danger"></span>
        </div>
        <div id="hidden" class="form-group" display="none">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" value=@Model.Id />
        </div>
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </form>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

CodeTheWay/CodeTheWay.Web.Ui/Views/Barrel/Index.cshtml
@model List<CodeTheWay.Web.Ui.Models.Barrel>
@*
    ViewData["Title"] = "Index";
*@
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
<script src="~/js/site.js"></script>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6"><h1 class="tableLinks">Index</h1></div>
        <div class="col-sm-5">
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for items.." title="Type in an item" class="tableInput" align="right">
        </div>
    </div>
    <table class="table sortable" id="myTable">
        <thead>
            <tr>
                <th scope="col">Radius</th>
                <th scope="col">Height</th>
                <th scope="col">Content</th>
                <th scope="col">Current Location</th>
                <th scope="col">Commands</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)

            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Radius)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Height)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentLocation)
                    </td>
                    <td>
                        <div>
                            <div>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                            </div>

                            <div>
                                @Html.ActionLink("Details", "Details", new { id = item.Id })
                            </div>
                            <div>
                             @*   <a href="/Barrel/Delete" class="delete" data-confirm="Are you sure to delete this item?">Delete</a> *@
                             @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('Are you sure you wish to delete this Barrel?');" })
                            </div>
                        </div>
                    </td>
                </tr>
              
            }
        </tbody>
    </table>

    <div>
        <a asp-action="Create" class="tableLinks"><b>Create a new barrel.</b></a>
    </div>
</div>

CodeTheWay/CodeTheWay.Web.Ui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodeTheWay/CodeTheWay.Web.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeTheWay.Web.Ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Run-Time Terror Co. Inc.</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Barrel" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Barrel" asp-action="Create">Create Barrel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CodeTheWay.Web.Ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>